export const HOME_CONTACT = {
  title_en: "Call us now",
  title_uz: "Hoziroq qo'ng'iroq qiling",
  title_ru: "Позвоните нам сейчас",
  title2_en: "WE ARE OPEN 24/7 FOR ASSISTANT",
  title2_uz: "BIZ 24/7 Yordam uchun ochiqmiz",
  title2_ru: "МЫ ОТКРЫТЫ 24/7 ДЛЯ ПОМОЩНИКА",
};

export const CONTACT_PAGE = {
  title_en: "Let's Stay Connected",
  title_uz: "Aloqada qolaylik",
  title_ru: "Давайте оставаться на связи",
  apply_en: "Apply now",
  apply_uz: "Hoziroq murojaat qiling",
  apply_ru: "Применить сейчас",
  title2_en:
    "Fill out the inputs below to ask any question or contact us using the details below",
  title2_uz:
    "Har qanday savol berish uchun quyidagi ma'lumotlarni to'ldiring yoki quyidagi tafsilotlardan foydalanib biz bilan bog'laning",
  title2_ru:
    "Заполните поля ниже, чтобы задать любой вопрос, или свяжитесь с нами, используя контактную информацию ниже.",
  cards: {
    card1: {
      title_en: "Email",
      title_uz: "Email",
      title_ru: "Электронная почта",
      desc_en: "Contact us using our email",
      desc_uz: "Elektron pochtamizdan foydalanib biz bilan bog'laning",
      desc_ru: "Свяжитесь с нами, используя нашу электронную почту",
    },
    card2: {
      title_en: "Phone number",
      title_uz: "Telefon raqam",
      title_ru: "Номер телефона",
      desc_en: "Call us any time",
      desc_uz: "Telefon raqam orqali biz bilan bog'laning",
      desc_ru: "Свяжитесь с нами по нашему номеру телефона",
    },
    card3: {
      title_en: "Office",
      title_uz: "Idora",
      title_ru: "Офис",
      desc_en: "Location of our office",
      desc_uz: "Ofisimiz joylashgan manzil",
      desc_ru: "Расположение нашего офиса",
    },
  },
  inputs: {
    first_name_en: "First name",
    first_name_uz: "Ism",
    first_name_ru: "Имя",
    last_name_en: "Last name",
    last_name_uz: "Familiya",
    last_name_ru: "Фамилия",
    email_en: "Email",
    email_uz: "Email",
    email_ru: "Электронная почта",
    phone_en: "Phone",
    phone_uz: "Telefon",
    phone_ru: "Номер телефона",
    message_en: "Message",
    message_uz: "Xabar",
    message_ru: "Сообщение",
    city_en: "City or state",
    city_uz: "Shahar yoki tuman",
    city_ru: "Город или штат",
    experience_en: "Years of experience",
    experience_uz: "Yillik tajriba",
    experience_ru: "Годы опыта",
    send_en: "Send message",
    send_uz: "Xabarni jo'natish",
    send_ru: "Отправить сообщение",
    apply_btn_en: "Apply",
    apply_btn_uz: "Yuborish",
    apply_btn_ru: "Применять",
  },
};
